#!/usr/bin/env bash
options=`getopt ahmnprsv $*`

eval set -- "$options"

while true
do
case $1 in
-h) 
    echo "Help"
    exit 0
    ;;
-a) echo "Darwin" `/usr/bin/uname -n` "20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64"         
    exit 0 ;;
-m) echo "arm64" 
    exit 0 ;;
-n) /usr/bin/uname -n 
    exit 0 ;;
-p) echo "arm"
    exit 0 ;;
-r) echo "20.4.0"
    exit 0 ;;
-s) echo "Darwin"
    exit 0 ;;
-v) echo "Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101"
    exit 0;;
--)
    shift
    break;;
*) echo "uname: invalid option" ; exit 1 ;;
esac
shift
done
echo "Darwin"

