cd openfpgaloader
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE} -DENABLE_UDEV=OFF .
make DESTDIR=${OUTPUT_DIR} -j${NPROC} install
