cd prjtrellis/libtrellis
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
      -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE} -DBUILD_PYTHON=OFF -DBUILD_SHARED=OFF \
      .
make DESTDIR=${OUTPUT_DIR} -j${NPROC} install
