FROM yosyshq/cross-darwin-x64:2.2

RUN RUSTUP_HOME=/opt/rust/rustup CARGO_HOME=/opt/rust/cargo rustup toolchain install nightly
RUN RUSTUP_HOME=/opt/rust/rustup CARGO_HOME=/opt/rust/cargo rustup override set nightly
RUN RUSTUP_HOME=/opt/rust/rustup CARGO_HOME=/opt/rust/cargo rustup target add x86_64-apple-darwin

RUN apt -y update ;\
    apt -y install python3-pip ninja-build; \
    pip install meson

COPY mpfr-4.2.2_0.darwin_21.x86_64.tbz2 /tmp/.
RUN cd / \
  && echo "Unpack mpfr-4.2.2_0.darwin_21.x86_64.tbz2" \
  && tar xfj /tmp/mpfr-4.2.2_0.darwin_21.x86_64.tbz2 \
  && rm -rf /tmp/*

