#!/usr/bin/env bash
options=`getopt ahmnprsv $*`

eval set -- "$options"

while true
do
case $1 in
-h) 
    echo "Help"
    exit 0
    ;;
-a) echo "Darwin" `/usr/bin/uname -n` "21.6.0 Darwin Kernel Version 21.6.0: Thu Nov  9 00:38:19 PST 2023; root:xnu-8020.240.18.705.10~1/RELEASE_X86_64 x86_64"
    exit 0 ;;
-m) echo "x86_64" 
    exit 0 ;;
-n) /usr/bin/uname -n 
    exit 0 ;;
-p) echo "i386"
    exit 0 ;;
-r) echo "21.6.0"
    exit 0 ;;
-s) echo "Darwin"
    exit 0 ;;
-v) echo "Darwin Kernel Version 21.6.0: Thu Nov  9 00:38:19 PST 2023; root:xnu-8020.240.18.705.10~1/RELEASE_X86_64"
    exit 0;;
--)
    shift
    break;;
*) echo "uname: invalid option" ; exit 1 ;;
esac
shift
done
echo "Darwin"

