FROM yosyshq/cross-linux-arm64:2.1

RUN apt purge --auto-remove cmake -y ;\
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null ;\
    echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null ;\
    apt-get update -y ;\
    apt-get install cmake -y;\
    apt -y autoremove ;\
    rm -rf /var/lib/apt/lists/*
