from src.base import Target

Target(
    name = 'default',
    release_name = 'oss-cad-suite',
    top_package = True,
    dependencies = [
        'yosys',
        'ghdl',
        'ghdl-yosys-plugin',
        'nextpnr-generic',
        'nextpnr-ice40',
        'nextpnr-ecp5',
        'nextpnr-machxo2',
        'nextpnr-nexus',
        'icestorm',
        'prjtrellis',
        'prjoxide',
        'dfu-util',
        'ecpprog',
        'openfpgaloader',
        'aiger',
        'avy',
        'bitwuzla',
        'boolector',
        'yices',
        'suprove',
        'pono',
        'z3',
        'mcy',
        'sby',
        'sby-gui',
        'gtkwave',
        'verilator',
        'iverilog',
        'ecpdap',
        'fujprog',
        'python-programmers',
        'openocd',
        'icesprog',
        'utils',
        'pyhdl',
        'cocotb',
    ],
    branding = 'OSS CAD Suite',
    readme = 'README',
    resources = [ 'system-resources' ],
)

Target(
    name = 'default-formal',
    release_name = 'oss-cad-suite-formal',
    top_package = True,
    dependencies = [
        'yosys',
        'avy',
        'bitwuzla',
        'boolector',
        'yices',
        'suprove',
        'pono',
        'z3',
        'mcy',
        'sby',
        'sby-gui',
        'gtkwave',
    ],
    branding ='OSS CAD Formal',
    readme = 'README',
    resources = [ 'system-resources' ],
)
