FROM yosyshq/cross-windows-x64:2.2

RUN RUSTUP_HOME=/opt/rust/rustup CARGO_HOME=/opt/rust/cargo rustup toolchain install nightly
RUN RUSTUP_HOME=/opt/rust/rustup CARGO_HOME=/opt/rust/cargo rustup override set nightly
RUN RUSTUP_HOME=/opt/rust/rustup CARGO_HOME=/opt/rust/cargo rustup target add x86_64-pc-windows-gnu

COPY tcl.pc /usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig/tcl.pc

RUN sudo dnf upgrade -y cmake libuv

RUN dnf install -y meson ninja-build

RUN wget https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz && \
    tar -xf gmp-6.3.0.tar.xz && \
    cd gmp-6.3.0 && \
    ./configure \
    --host=x86_64-w64-mingw32 \
    --prefix=/usr/x86_64-w64-mingw32/sys-root/mingw \
    --enable-static \
    --disable-shared \
    --with-pic && \
    make -j$(nproc) && \
    sudo make install

RUN wget https://www.mpfr.org/mpfr-4.2.1/mpfr-4.2.1.tar.xz && \
    tar xf mpfr-4.2.1.tar.xz && \
    cd mpfr-4.2.1 && \
    ./configure \
    --host=x86_64-w64-mingw32 \
    --prefix=/usr/x86_64-w64-mingw32/sys-root/mingw \
    --disable-shared \
    --enable-static \
    --with-gmp=/usr/x86_64-w64-mingw32/sys-root/mingw && \
    make -j$(nproc) && \
    sudo make install
